### ISSUE TITLE
Org-Conversations: Hierarchical LLM Chatting Within Org-Mode

### ISSUE THREAD

**Issue by NightMachinery** [ultronozm/ai-org-chat.el#1]
If you find the time, take a look at https://github.com/karthink/gptel/discussions/457#discussioncomment-11141955 .

**Comment by ultronozm** [comment]
Thanks for letting me know

**Comment by ultronozm** [comment]
In my haste, I missed that you're the author of both this issue and that issue, so I thought you were just suggesting that I point out that this package exists. Oops! Was there something more specific you were hoping for feedback on?

**Comment by NightMachinery** [comment]
@ultronozm No, I just wanted to see if you had any feedback. Thanks!

**Comment by ultronozm** [comment]
Here are some quick thoughts on your proposal, comparing to the way I've done things in my package:

**Message types**: the mark-up in your proposal seems a bit heavy to me.  Reading further, I see that the point of it is to allow siblings to contribute to the conversation history, so as to avoid long nested chains.  Personally, I haven't had any issue with such chains.  They're simple enough to navigate using C-c C-n, C-c C-p, C-c C-u, etc., and the corresponding org speed keys.

**Grouping messages**: I sometimes put similar conversations in similar files, with the top-level headings renamed to indicate their content, but often just do one conversation per file.

**Traversal**: I've used the current narrowing restriction to determine when to stop the traversal.  I have sometimes found it convenient to vary this on the fly.

**Skipping subtree**: any "uncle" trees are automatically skipped in my setup.

**Headings**: I ignore these.

**Property stripping**: I do this.  Properties are used to specify context and tools.

**Property hierarchy**: this is how the relevant context/tools are assembled in my setup.

**Model selection**: I prefer to keep the choice of model (and other parameters) decoupled from the text.  For instance, sometimes Claude gets overloaded, so I switch to OpenAI for a bit and then later revisit with Claude, generating responses to identical prompts with different models.  I see the beauty in making the setup reproducible by recording all parameters in the file, but after experimenting, found that I didn't gain anything in practice from doing so.  It would be easy to do so via a :MODEL property if anyone wanted such a feature.
